# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96930bb8c8f756c52be5689b5ea7b7da9c9b7c0dd023e6ed997e00f9f1a2d3e0e659ea6911f80bcccdf1b6dd58e90e61c25a66a6d521d1097fb5ecd0c85eade0

test:
  secret_key_base: 9f5a1e33d73be8e819f05fe50dacd6ecd7bdb877606f91fc89022459f539d552ec9f2ea5dea37afed2d17fdf721210f89253bfc341ac2a80f113eb241859e654

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
